# Force dep to vendor the code generators, which aren't imported just used at dev time.
required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/gengo/args",
  "github.com/onsi/ginkgo", # for test framework
  "github.com/onsi/gomega", # for test matchers
  "sigs.k8s.io/controller-tools/cmd/controller-gen", # for crd/rbac generation
]

ignored = [
  # "github.com/keleustes/armada-operator/pkg/helmv2",
  "github.com/keleustes/armada-operator/pkg/helmv3",
  "helm.sh/helm/pkg/kube",
  "helm.sh/helm/pkg/storage",
  "helm.sh/helm/pkg/storage/driver",
  "helm.sh/helm/pkg/release",
  "helm.sh/helm/pkg/chart",
]

# For dependency below: Refer to issue https://github.com/golang/dep/issues/1799
[[override]]
name = "gopkg.in/fsnotify.v1"
source = "https://github.com/fsnotify/fsnotify.git"
version="v1.4.7"

[[override]]
  name = "k8s.io/code-generator"
  # version = "=v0.1.9"
  # revision for tag "kubernetes-1.12.3"
  revision = "3dcf91f64f638563e5106f21f50c31fa361c918d"

[[override]]
  name = "k8s.io/kubernetes"
  version = "=1.13.4"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/cli-runtime"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "0cf8f7e6ed1d2e3d47d02e3b6e559369af24d803"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  version = "=v0.1.10"

[[constraint]]
  name = "github.com/sergi/go-diff"
  version = "1.0.0"

[[override]]
  name = "github.com/coreos/prometheus-operator"
  version = "=v0.26.0"

[[constraint]]
  name = "github.com/operator-framework/operator-sdk"
  # The version rule is used for a specific release and the master branch for in between releases.
  branch = "master" #osdk_branch_annotation
  # version = "=v0.4.0" #osdk_version_annotation

[[constraint]]
  name = "k8s.io/helm"
  version = "=v2.13.0"
  # name = "helm.sh/helm"
  # source = "https://github.com/helm/helm.git"
  # branch = "dev-v3"

# We need overrides for the following imports because dep can't resolve them
# correctly. The easiest way to get this right is to use the versions that
# k8s.io/helm uses. See https://github.com/helm/helm/blob/v2.12.0-rc.1/glide.lock
[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/docker/docker"
  revision = "a9fbbdc8dd8794b20af358382ab780559bca589d"

[prune]
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    non-go = false
