apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: armadachartgroups.armada.airshipit.org
spec:
  additionalPrinterColumns:
  - JSONPath: .status.actual_state
    description: State
    name: State
    type: string
  - JSONPath: .spec.target_state
    description: Target State
    name: Target State
    type: string
  - JSONPath: .status.satisfied
    description: Satisfied
    name: Satisfied
    type: boolean
  group: armada.airshipit.org
  names:
    kind: ArmadaChartGroup
    plural: armadachartgroups
    shortNames:
    - acg
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            description:
              description: description of chart set
              type: string
            name:
              description: Name of the chartgroup
              type: string
            revisionHistoryLimit:
              description: revisionHistoryLimit is the maximum number of revisions
                that will be maintained in the ArmadaChartGroup's revision history.
                The revision history consists of all revisions not represented by
                a currently applied ArmadaChartGroupSpec version. The default value
                is 10.
              format: int32
              type: integer
            sequenced:
              description: enables sequenced chart deployment in a group
              type: boolean
          type: object
        status:
          properties:
            conditions:
              description: 'List of conditions and states related to the resource.
                JEB: Feature kind of overlap with event recorder'
              items:
                properties:
                  lastTransitionTime:
                    format: date-time
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  resourceName:
                    type: string
                  resourceVersion:
                    format: int32
                    type: integer
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            reason:
              description: Reason indicates the reason for any related failures.
              type: string
            satisfied:
              description: Satisfied indicates if the release's ActualState satisfies
                its target state
              type: boolean
          required:
          - satisfied
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
